name: reusable / Docker Build and Publish

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

permissions:
  contents: read

jobs:
  hello:
    name: Hello
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print app name
        run: |
          echo "app name: ${{ vars.APP_NAME }}"
